In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
from heptracktool.io.muon_collider_track_data import MuonColliderTrackDataReader

In [3]:
input_dir = "/global/cfs/cdirs/m3443/data/TrackingInMuonCollider/singleMuon"
output_dir = "/global/cfs/cdirs/m3443/data/TrackingInMuonCollider/singleMuon_feature_store"
reader = MuonColliderTrackDataReader(
    input_dir=input_dir,
    output_dir=output_dir,
    overwrite=False)

Total 1000 events in directory: /global/cfs/cdirs/m3443/data/TrackingInMuonCollider/singleMuon

In [4]:
reader.read(0);

read event 1, using file /global/cfs/cdirs/m3443/data/TrackingInMuonCollider/singleMuon/Hits_TTree_001_0-0.root

In [9]:
reader.spacepoints

,x,y,z,toa,energy,is_from_secondary,particle_id
0,26.867790,-13.960361,28.854168,0.153366,0.000017,0.0,123
1,28.691584,-14.914240,30.820835,0.172180,0.000040,0.0,123
2,45.474228,-23.657135,48.854168,0.213092,0.000029,0.0,123
3,-31.823210,7.353825,62.937500,0.237282,0.000024,1.0,0
4,-30.539627,10.452671,56.787502,0.210621,0.000022,1.0,0
...,...,...,...,...,...,...,...
5600372,-1097.659546,-505.500885,-1884.148560,7.481524,0.000044,1.0,0
5600373,827.776001,584.436890,-1615.851440,6.481364,0.000080,1.0,0
5600374,835.116028,591.297974,-1615.851440,6.416124,0.000043,1.0,0
5600375,-983.222656,-281.205414,-1884.148560,7.395607,0.000027,1.0,0
5600376,-686.627747,443.828857,-1311.148560,5.222860,0.000036,1.0,0

In [10]:
reader.spacepoints[reader.spacepoints["is_from_secondary"] == 0.0]

,x,y,z,toa,energy,is_from_secondary,particle_id
0,26.867790,-13.960361,28.854168,0.153366,0.000017,0.0,123
1,28.691584,-14.914240,30.820835,0.172180,0.000040,0.0,123
2,45.474228,-23.657135,48.854168,0.213092,0.000029,0.0,123
276942,74.598175,-38.786968,80.139999,0.404660,0.000025,0.0,123
276943,76.500443,-39.787418,82.190002,0.411962,0.000115,0.0,123
1145589,112.698181,-58.612354,121.110001,0.522346,0.000051,0.0,123
1145590,301.677704,-156.846893,323.709991,1.577902,0.000056,0.0,123
1145591,493.870422,-256.745911,530.479980,2.631756,0.000031,0.0,123
3841068,725.034912,-376.904816,778.969971,3.730798,0.000083,0.0,123
3841069,1021.487183,-530.926941,1100.069946,5.318267,0.000054,0.0,123
3841070,1026.409180,-533.427246,1100.069946,5.400998,0.000008,0.0,123
4904696,1216.836182,-632.215759,1305.148560,6.296968,0.000043,0.0,123
4904697,1222.240479,-635.314392,1311.148560,6.361698,0.000033,0.0,123

In [5]:
reader.particles

,par_vx,par_vy,par_vz,par_px,par_py,par_pz,par_id,par_pdg_id,par_charge,part_id
0,-0.0,0.0,0.0,3723.709717,-1936.417969,4000.519775,0.0,13.0,-1.0,123

In [12]:
import uproot

file_name = "/global/cfs/cdirs/m3443/data/TrackingInMuonCollider/singleMuon/Hits_TTree_001_0-0.root"
tree = uproot.open(file_name)["HitTree"]

In [13]:
from heptracktool.io import utils_mcollider_data as utils

In [14]:
event_info = tree.arrays(list(utils.translator.keys()), library="np")  # type: ignore

In [17]:
event_info["Hit_x"][0].shape

(5600377,)

In [7]:
tree["MCP_PDGID"].array(library="np")

array([array([13.], dtype=float32)], dtype=object)

In [12]:
hit_x = tree["Hit_x"].array(library="np")

In [16]:
hit_x

array([array([  26.86779 ,   28.691584,   45.474228, ...,  835.116   ,
              -983.22266 , -686.62775 ], shape=(5600377,), dtype=float32)],
      dtype=object)

In [17]:
from pathlib import Path
import re

inputdir = Path("/global/cfs/cdirs/m3443/data/TrackingInMuonCollider/singleMuon")
all_evts = list(inputdir.glob("*.root"))

file_name_pattern = "Hits_TTree_([0-9]+)_([0-9]+)-([0-9]+).root"
all_evtids = sorted([
    int(re.search(file_name_pattern, x.name).group(1).strip()) for x in all_evts
])